### ISSUE TITLE
Openshift NuGet Error Dot Net Core 2.0

### ISSUE THREAD

**Issue by ManuelAVR** [redhat-developer/s2i-dotnetcore#196] opened 2018-06-20 07:44 UTC
I have a big problem with Openshift and Nuget.

First of all I wanted to create a Dot Net Core 2.0 solution. So I create a new project with API and Core 2.0.

Then I upload the solution to the repository on GitLab. 

We have a VPN connection to our network that is private.

Everything works well until the MSBuild start and here is the log

Using SDK: 2.0.3

280 ---> Copying application source ...

281 ---> Restoring application dependencies...

282 Restoring packages for /opt/app-root/src/fassi_studio_v2/fassi_studio_v2.csproj...

283 Restoring packages for /opt/app-root/src/fassi_studio_v2/fassi_studio_v2.csproj...

284 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json . [/opt/app-root/src/fassi_studio_v2/fassi_studio_v2.csproj]

285 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : An error occurred while sending the request. [/opt/app-root/src/fassi_studio_v2/fassi_studio_v2.csproj]

286 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Failure when receiving data from the peer [/opt/app-root/src/fassi_studio_v2/fassi_studio_v2.csproj]

287 error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnet-20-rhel7@sha256:81ec2cf307a686d5fc7bd79ebc82d831b05c45602368bc477f20506ef6c9c0fc

And now the problem:

Doesn't matter if I include NuGet.Config and change the source. Doesn't matter if I override the enviroment variable DOTNET_RESTORE_RESOURCES The build is always using : https://api.nuget.org/v3/index.json And, I guess because of our interne proxy the connection is refused.

-----------------------------

Update:

We have change the Enviroment Variable DOTNET_RESTORE_RESOURCES to our private NuGet  but now we geht another error. The container try to retrieve and use a FindById()..... with the address we give and that makes a error. 

Restoring packages for /opt/app-root/src/core_mono_sql1/core_mono_sql1.csproj...
 
283 Retrying 'FindPackagesByIdAsyncCore' for source 'https://bahnhub.tech.rz.db.de:443/artifactory/nuget-api-v3-remote-cache/Packages/FindPackagesById()?id='Microsoft.NETCore.Platforms'' .
 
284 An error occurred while sending the request.
 
285 SSL connect error
 
286 Retrying 'FindPackagesByIdAsyncCore' for source 'https://bla/bla/Packages/FindPackagesById()?id='Microsoft.NETCore.App'' .
 
287 An error occurred while sending the request.
 
288 Peer certificate cannot be authenticated with given CA certificates
 
289 Retrying 'FindPackagesByIdAsyncCore' for source 'https://bla/bla/Packages/FindPackagesById()?id='Microsoft.NETCore.Platforms'' .
 
290 An error occurred while sending the request.
 
291 Peer certificate cannot be authenticated with given CA certificates
 
292 Retrying 'FindPackagesByIdAsyncCore' for source 'https://bla/bla/Packages/FindPackagesById()?id='Microsoft.NETCore.App'' .
 
293 An error occurred while sending the request.
 
294 Peer certificate cannot be authenticated with given CA certificates
 
295 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Failed to retrieve information about 'Microsoft.NETCore.Platforms' from remote source 'https://bla/bla/Packages/FindPackagesById()?id='Microsoft.NETCore.Platforms'' . [/opt/app-root/src/core_mono_sql1/core_mono_sql1.csproj]
 
296 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   An error occurred while sending the request. [/opt/app-root/src/core_mono_sql1/core_mono_sql1.csproj]
 
297 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   Peer certificate cannot be authenticated with given CA certificates [/opt/app-root/src/core_mono_sql1/core_mono_sql1.csproj]
 
Another idea is to use the nuget.config file but I read that must be in the container and not in the code.

Have someone an Idea? Thank you so much!

**Comment by tmds** [comment] 2018-06-20 10:28
hi @ManuelAVR , thanks for bringing the issue to this repo.

From your update it looks like `DOTNET_RESTORE_RESOURCES` is now working as expected.

The new issue is that the local nuget server's certificate is not trusted by the build container.

> error : Peer certificate cannot be authenticated with given CA certificates

If your server is accessible via http, changing the scheme in DOTNET_RESTORE_RESOURCES should make things work.

If it is only https accessible, things are more challenging.
.NET Core 2.0 doesn't allow to easily provide additional certificates.
With .NET Core 2.1, additional certificate authorities can be specified via the SSL_CERT_FILE envvar. You need to make a PEM bundle file that contains your CA and point the envvar to that bundle.
We are looking to backport the feature to 2.0, but I don't know the ETA.

Is using 2.1 an option for you?

CC @omajid

**Comment by ManuelAVR** [comment] 2018-06-20 13:39
Thanks for the answer! Yes, we can try to use 2.1 this is not a problem but
I want to share with you our workaround because this problem was really bad...
The main problem is that our VPN is private and openshift work inside, then it need proxy information to connect to nuget and there is no way to give this information.
Then with our private server we have SSL problem and also this dlls packages that we need are not yet there...



WORKAROUND: install local pkges and force the app to use this installation via nuget.config:

``

**Comment by tmds** [comment] 2018-06-20 14:09
> The main problem is that our VPN is private and openshift work inside, then it need proxy information to connect to nuget and there is no way to give this information.

Can you set the HTTPS_PROXY envvar? Or do you need to provide more information?

> Then with our private server we have SSL problem and also this dlls packages that we need are not yet there...

This should work with the SSL_CERT_FILE on .NET Core 2.1.
If the packages you are missing are on nuget.org, some servers support working as a caching server.

**Comment by ManuelAVR** [comment] 2018-06-21 13:18
Ok, How can I set exactly the proxy; I tried different things but nothing work. We have user pass as auth.

**Comment by tmds** [comment] 2018-06-21 15:04
> Do you know how to set this certificate?

You need to get the CA cert from the server.
Running `openssl s_client -showcerts -connect host:port </dev/null` should give you some certificates.
Copy the last certificate (including `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`).
This is what you need to put in a file and reference using SSL_CERT_FILE.
Try to get this to work on a Linux machine before you try to make it work on OpenShift.

To check your file, you can use a program like this:
```cs
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace console
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync("https://host:port");
                System.Console.WriteLine(response.StatusCode);
            }
        }
    }
}
```
If you `dotnet run` this, you should see the exception:
```
Unhandled Exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
...
```
If you run it pointing `CA_CERT_FILE` to your certificate file, it should work:
```
$ SSL_CERT_FILE=./cacert.pem dotnet bin/Release/netcoreapp2.0/console.dll
OK
```

**Comment by tmds** [comment] 2018-07-04 11:36
@ManuelAVR can you give an update?

I'm adding a feature to s2i-dotnetcore which will make it simpler to trust such certificates via a well documented envvar (https://github.com/redhat-developer/s2i-dotnetcore/pull/199).
You'll be able to put the certificates in a folder (e.g. certificates) and set DOTNET_SSL_DIRS (e.g. DOTNET_SSL_DIRS=certificates).

**Comment by ManuelAVR** [comment] 2018-07-05 07:59
Hello! Sorry, the current State is that we cant use this. The only way it is working is without nugget to download. No artifactory no nugget neither are working. The proxy is the problem. Even when using artifactory he redirect us to v3 from nugget and he can’t download it. I will try again with the new envvar thank for this.

**Comment by tmds** [comment] 2018-07-05 08:04
> I will try again with the new envvar thank for this.

The envvar is not available yet. It will be part of the next respin of the image, which matches the .net core patch releases.

> Even when using artifactory he redirect us to v3 from nugget and he can’t download it.

**Comment by ManuelAVR** [comment] 2018-07-05 08:42
Wait I will write you again the logs from the build with the different configs from Nuget.Config and you can see it yourself because it is a bit complicated to explain.

**Comment by ManuelAVR** [comment] 2018-07-05 09:08
So for the Nugget.config first try with normal Http and the enviroment variable HTTP_PROXY and version 3 for protocol:

`<packageSources>
    <clear/>
    <add key="nuget.org" value="http://api.nuget.org/v3/index.json" protocolVersion="3"/>
<packageSources>`

Build Output:


Cloning "https://blablabla.git " 

  | Commit:	XXXX (Update NuGet.config)
  | Author:	blablabla
  | Date:	Thu Jul 5 08:51:39 2018 +0000
  | Using HTTP proxy http://xxx  and HTTPS proxy http://yyy  for script download 

> This proxys are not set by me.

  | ---> Installing npm tools ...
  | ---> Setting npm http proxy
  | ---> Setting npm https proxy
  | ~ ~/src
  | npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
  | npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
  | npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
  | npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
  | npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
  | npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

/opt/app-root

  | +-- bower@1.8.4
  | `-- gulp@3.9.1
  | +-- archy@1.0.0
  | +-- chalk@1.1.3

... and more of this until

npm WARN enoent ENOENT: no such file or directory, open '/opt/app-root/package.json'

  | npm WARN app-root No description
  | npm WARN app-root No repository field.
  | npm WARN app-root No README data
  | npm WARN app-root No license field.
  | ~/src

> Here come the nice errors

  | Using SDK: 2.0.3
  | ---> Copying application source ...
  | ---> Restoring application dependencies...
  | Restoring packages for /opt/app-root/src/CoreApiTest.csproj...
  | Restoring packages for /opt/app-root/src/CoreApiTest.csproj...
  **| /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Unable to load the service index for source http://api.nuget.org/v3/index.json . [/opt/app-root/src/CoreApiTest.csproj]
  | /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   Response status code does not indicate success: 403 (Forbidden).** [/opt/app-root/src/CoreApiTest.csproj]
  | error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnet-20-rhel7@sha256:81ec2cf307a686d5fc7bd79ebc82d831b05c45602368bc477f20506ef6c9c0fc

**Comment by tmds** [comment] 2018-07-05 09:30
> http://api.nuget.org/v3/index.json

If you put http in here, the nuget.org site redirects you to https. It is best to to use the https scheme to eliminate the redirect.

> This proxys are not set by me.

I think your OpenShift installation probably has proxies configured. So they get picked up by git, and then npm is also able to use them. But .net fails.
You can check these variables are set by changing DOTNET_VERBOSITY to something (for example, `normal`). Then at the top it will print out the variables.

> Response status code does not indicate success: 403 (Forbidden).

Forbidden, this is probably the proxy server which doesn't allow you to access api.nuget.org.

**Comment by ManuelAVR** [comment] 2018-07-05 09:38
So... I have set verbosity as you said and this is what it comes:


ASPNETCORE_URLS=http://*:8080
--
  | CONTAINER_SCRIPTS_PATH=/opt/app-root
  | CPATH=/opt/rh/rh-dotnet20/root/usr/include
  | DOTNET_APP_PATH=/opt/app-root/app
  | DOTNET_ASSEMBLY_NAME=
  | DOTNET_CLI_TELEMETRY_OPTOUT=true
  | DOTNET_CONFIGURATION=Release
  | DOTNET_CORE_VERSION=2.0
  | DOTNET_DEFAULT_CMD=default-cmd.sh
  | DOTNET_FRAMEWORK=netcoreapp2.0
  | DOTNET_NPM_TOOLS=bower gulp
  | DOTNET_PUBLISH=true
  | DOTNET_RUNNING_IN_CONTAINER=true
  | DOTNET_SDK_BASE_VERSION=2.0.0
  | DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  | DOTNET_STARTUP_PROJECT=
  | DOTNET_TEST_PROJECTS=
  | DOTNET_USE_POLLING_FILE_WATCHER=true
  | DOTNET_VERBOSITY=normal
  | ENABLED_COLLECTIONS=rh-dotnet20 rh-nodejs6
  | HOME=/opt/app-root
  | HOSTNAME=apidotnet-59-build

>   | HTTPS_PROXY=http://PROXY that I set
>   | HTTP_PROXY=http://PROXY that I set

  | LD_LIBRARY_PATH=/opt/rh/rh-nodejs6/root/usr/lib64:/opt/rh/rh-dotnet20/root/usr/lib64
  | MANPATH=/opt/rh/rh-nodejs6/root/usr/share/man:/opt/rh/rh-dotnet20/root/usr/share/man:
  | NO_PROXY=.internal addresses
  | NUGET_XMLDOC_MODE=skip
  | OPENSHIFT_BUILD_COMMIT=2de00ab2fbc654e2e518d699fb20c95db4ddf211
  | OPENSHIFT_BUILD_NAME=apidotnet-59
  | OPENSHIFT_BUILD_NAMESPACE=fassi-eu
  | OPENSHIFT_BUILD_SOURCE=https://mygit
  | PATH=/opt/rh/rh-nodejs6/root/usr/bin:/opt/rh/rh-dotnet20/root/usr/bin:/opt/rh/rh-dotnet20/root/usr/sbin:/opt/app-root/src/.local/bin:/opt/app-root/src/bin:/opt/app-root/node_modules/.bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  | PKG_CONFIG_PATH=/opt/rh/rh-dotnet20/root/usr/lib64/pkgconfig
  | PWD=/opt/app-root/src
  | PYTHONPATH=/opt/rh/rh-nodejs6/root/usr/lib/python2.7/site-packages:/opt/rh/rh-dotnet20/root
  | SHLVL=2
  | STI_SCRIPTS_PATH=/usr/libexec/s2i
  | XDG_DATA_DIRS=/opt/rh/rh-dotnet20/root/usr/share:/usr/local/share:/usr/share
  | X_SCLS=rh-nodejs6 rh-dotnet20
  | _=/usr/bin/env
  | container=oci

>   | http_proxy=http:// I didnt set this one!!! 
>   | https_proxy=http:// I didnt set this one!!! 
 
no_proxy=.amazonaws.com,.cluster.local,.db.de,.intranet.deutschebahn.com,.svc,10.0.0.0/8,10.193.0.0/16,10.193.184.125,169.254.169.254,ip-10-104-104-137.eu-central-1.compute.internal,ip-10-104-104-25.eu-central-1.compute.internal,ip-10-104-104-42.eu-central-1.compute.internal,ip-10-104-104-66.eu-central-1.compute.internal,ip-10-104-105-100.eu-central-1.compute.internal,ip-10-104-105-103.eu-central-1.compute.internal,ip-10-104-105-222.eu-central-1.compute.internal,ip-10-104-105-3


maybe my proxy is overwriten? Do you know how to control this?

**Comment by ManuelAVR** [comment] 2018-07-05 10:52
OK I went a little bit farther, I overwrite the http_proxy and https_proxy (the second one) and now I am getting:


1>/opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json . [/opt/app-root/src/CoreApiTest.csproj]

  | /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/NuGet.targets(102,5): error :   Response status code does not indicate success: 407 (Proxy Authentication Required). [/opt/app-root/src/CoreApiTest.csproj]

The point here is that I wrote both proxies like:
HTTP_PROXY=http://username:password@proxy:port
HTTPS_PROXY=http://username:password@proxy:port
http_proxy = http://username:password@proxy:port
https_proxy = http://username:password@proxy:port

why is he asking me for authentication  again if it has already one?

**Comment by tmds** [comment] 2018-07-05 11:13
Can you see how this behaves for 2.1?
Some things changed for 2.1 which may cause it to work, or fail in a different way...
It would be best if we make this work for 2.1, because 2.0 will be EOL in October.

**Comment by ManuelAVR** [comment] 2018-07-05 11:44
Ok I just tried your project 2.1 (https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-2.1/app) and here it is:


---> Restoring application dependencies...
--
  | /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/opt/app-root/src/app/app.csproj]
  | /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.3/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/opt/app-root/src/app/app.csproj]

That  means that the server doesnt have the version 2.1 sdk? or what I am doing wrong?

**Comment by tmds** [comment] 2018-07-05 11:55
You need to change your build config so it uses the dotnet:2.1 image instead of the dotnet:2.0 image.

**Comment by ManuelAVR** [comment] 2018-07-05 12:35
This is on Image Configuration right? 

Image stream Tag
Build from
openshift/dotnet: Here I can only choose 1.0 1.1 2.0 or latest that is 2.0
there is no 2.1...

**Comment by tmds** [comment] 2018-07-05 12:47
2.1 was not available yet when your version of OpenShift was released.

You can import the image streams in your project. You can do it in the web UI via Add to project > Import YAML / JSON. Then import this: https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/dotnet_imagestreams.json.

Since this imports into your project, to reference the imagestream you need to change namespace to your project name (e.g. myproject below). Go to your Build and then select Edit YAML and update the from.name and from.namespace.
```
  strategy:
    sourceStrategy:
      env:
...
      from:
        kind: ImageStreamTag
        name: 'dotnet:2.1'
        namespace: myproject
```

**Comment by ManuelAVR** [comment] 2018-07-05 13:19
So I manage to do everything and I put all the variables with your example code but... NO WAY

---> Restoring application dependencies...
--
  | Build started 07/05/2018 13:16:34.
  | 1>Project "/opt/app-root/src/app/app.csproj" on node 1 (Restore target(s)).
  | 1>Restore:
  | Restoring packages for /opt/app-root/src/app/app.csproj...
  | 1>/opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json . [/opt/app-root/src/app/app.csproj]
  | /opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authentication Required). [/opt/app-root/src/app/app.csproj]
  | 1>Done Building Project "/opt/app-root/src/app/app.csproj" (Restore target(s)) -- FAILED.

Proxy is set and I check it... this is a little bit frustrating now. How can be so difficult to configurate a proxy?

**Comment by tmds** [comment] 2018-07-05 14:59
I think this may be a bug/missing feature. I'll create an issue in corefx repo and CC you.

**Comment by ManuelAVR** [comment] 2018-07-05 15:06
Thank you so much. Lets make this work! :D

**Comment by ManuelAVR** [comment] 2018-07-06 19:39
Thanks! I will try to reproduce it and i will come back.

**Comment by ManuelAVR** [comment] 2018-07-09 22:19
So, after testing it in a linux machine this is the output.

_1. I did the curl without proxy and the output:_

* Rebuilt URL to: http://www.redhat.com/
*   Trying 1.1.1.1.1...
* TCP_NODELAY set
* Connected to proxy (1.1.1.1) port 1111 (#0)
> GET http://www.redhat.com/ HTTP/1.1
> Host: www.redhat.com
> User-Agent: curl/7.59.0
> Accept: */*
> Proxy-Connection: Keep-Alive 
< HTTP/1.1 407 Proxy Authentication Required
< Date: Mon, 09 Jul 2018 21:36:48 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3449
< X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
< Vary: Accept-Language
< Content-Language: en
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM
< Connection: close

_2.Then I did it with the credentials as you said (**without taking into account that the auth is NTLM**)_ 

curl -v -H "Proxy-Authorization: Basic $credentials"  http://www.redhat.com --proxy ourproxy:port

And I got this error again

_3. I Tried this time with NTLM_

curl --proxy-ntlm --proxy-user $user:$password --url www.redhat.com --proxy ourproxy:port

and I got: 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.redhat.com/">here</a>.</p>
</body></html>
```

So like this is working with our proxy.

**Comment by tmds** [comment] 2018-07-10 07:34
Can you see what happens when you set `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` in your container? This uses the libcurl handler (same as 2.0) instead of a new managed http handler (introduced in 2.1).

**Comment by ManuelAVR** [comment] 2018-07-10 08:47
Same error as before:


1>Project "/opt/app-root/src/app/app.csproj" on node 1 (Restore target(s)).
--
  | 1>Restore:
  | Restoring packages for /opt/app-root/src/app/app.csproj...
  | 1>/opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json . [/opt/app-root/src/app/app.csproj]
  | /opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authentication Required). [/opt/app-root/src/app/app.csproj]
  | 1>Done Building Project "/opt/app-root/src/app/app.csproj" (Restore target(s)) -- FAILED.
  |  
  | Build FAILED.
  |  
  | "/opt/app-root/src/app/app.csproj" (Restore target) (1) ->
  | (Restore target) ->
  | /opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json . [/opt/app-root/src/app/app.csproj]
  | /opt/rh/rh-dotnet21/root/usr/lib64/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authentication Required). [/opt/app-root/src/app/app.csproj]
  |  
  | 0 Warning(s)
  | 1 Error(s)
  |  
  | Time Elapsed 00:00:01.64
  | error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnet-21-rhel7@sha256:160a29dca8a2f96db971c1c3686e2f8acb80d57fb493d2a463fc284d7deba666

**Comment by tmds** [comment] 2018-07-10 09:49
Does `curl` work when you use 'Negotiate'?

Let's try to see what .NET Core is doing, on your Linux system (using 2.1, without setting DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER):
```cs
using System;
using System.Net.Http;

namespace console
{
    class Program
    {
        static void Main(string[] args)
        {
            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.AllowAutoRedirect = false;
            using (var httpClient = new HttpClient(httpClientHandler))
            {
                httpClient.GetAsync("http://www.redhat.com").GetAwaiter().GetResult();
            }
        }
    }
}
```

Build it:
```
dotnet build -c Release
```

and then strace:
```
http_proxy=http://yourproxy:port strace -f -e sendmsg,recvmsg -s 2000 dotnet bin/Release/netcoreapp2.1/console.dll
```
in the output near the end you should see the `sendmsg` and `recvmsg` calls between your machine and the proxy server.

**Comment by ManuelAVR** [comment] 2018-07-10 14:23
We have tried all the steps that you said and this is the output.

> Does curl work when you use 'Negotiate'?

We tried from the linux machine connected to the VPN:

curl --negotiate --user-proxy $user:$password --proxy proxy:port --url http://www.redhat.com

and this give us the same problem as always. It only works with --proxy-ntlm on it.

> Let's try to see what .NET Core is doing, on your Linux system

We install all the required sdks and create the project, then we run it as you said and in the attach file can you find the result. 

[tracedotnet.txt](https://github.com/redhat-developer/s2i-dotnetcore/files/2180728/tracedotnet.txt)

**Comment by tmds** [comment] 2018-07-10 14:38
The corefx implementation for picking a scheme is here: https://github.com/dotnet/corefx/blob/fe5927a0f68717223528220c891a3b02d7331829/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs#L105-L108.
It tries in this order schemes which the server sent (via Proxy-Authenticate): negotiate, ntlm, digest and basic.
If negotiate fails, it will not try another.

> curl --negotiate --user-proxy $user:$password --proxy proxy:port --url http://www.redhat.com

maybe this should be --proxy-negotiate?

> tracedotnet.txt

can you run this with a user and password in the http_proxy? You don't need to send me the trace (since it includes sensitive info). You can look for the `Proxy-Authorization` string and see what scheme(s) it is trying.

**Comment by ManuelAVR** [comment] 2018-07-10 15:19
We tried, of course, proxy-negotiate also and give us the same output.

For the command (with the proxy user:pass integrated):  

> curl -v --proxy-negotiate --url https://api.nuget.org/v3/index.json --proxy $http_proxy

Answer:

< Proxy-Authenticate: Negotiate
* gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate. 
< Proxy-Authenticate: NTLM

Same with 

> curl -v --proxy-ntlm --url https://api.nuget.org/v3/index.json --proxy $http_proxy 

Everything works fine.

Now with same config but with your example

> http_proxy=$http_proxy strace -f -e sendmsg,recvmsg -s 2000 dotnet bin/Release/netcoreapp2.1/console.dll

It is always: 

< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM

We need a way to configure this feature.

**Comment by tmds** [comment] 2018-07-10 17:02
> gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.

so curl doesn't work with negotiate either?

> It is always:
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM

What is `Proxy-Authorization`  sent from the client to the proxy server?

**Comment by tmds** [comment] 2018-07-11 08:23
> We need a way to configure this feature.

Since it looks like an issue with the negotiate mechanism, I doubt we'll be able to fix it without changes to the image/.NET Core. To get this working, the best option is to configure your local NuGet server so it caches instead of redirects.

**Comment by ManuelAVR** [comment] 2018-07-11 09:12
> What is Proxy-Authorization sent from the client to the proxy server?

This is the only thing the client is sending 

> sendmsg(34, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="GET http://www.redhat.com/ HTTP/1.1\r\nHost: www.redhat.com\r\n\r\n", iov_len=61}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) 

So that means in a future version?

Ok and how is this with the Cache working? We have already an artifactory server but I tried and it produces in the end the same problems.

Do you know how to stablish this local NuGet cache server or how to use it?

**Comment by tmds** [comment] 2018-07-11 09:33
> This is the only thing the client is sending

After the negotiate mechanism fails on the client, no attempts are made to authenticate.

> So that means in a future version?

Yes. This needs to be reported as an issue.
Did I understand correctly that `--proxy-negotiate` with curl fails with the `gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.` message?
This happens probably also with `--proxy-anyauth`?

> Ok and how is this with the Cache working? We have already an artifactory server but I tried and it produces in the end the same problems.

I'm not familiar with Artifactory. But I guess it may be a setting. From the docs, it looks like you need to add a 'remote repository'. I'm not sure what settings are available to configure that further. If you have some Artifactory support, please check with them. I think this is possible with Sonatype Nexus, but Artifactory probably supports this too.

**Comment by tmds** [comment] 2018-07-12 08:04
After further investigation (https://github.com/dotnet/corefx/issues/31005), the root cause is .NET Core on RHEL does not support Windows auth due to missing gss-ntlmssp. I created https://bugzilla.redhat.com/show_bug.cgi?id=1600392 for this.

I hope you are able to configure your Artifactory server as a caching server. If not, can you create a support ticket with Red Hat. Our support engineers may have more experienced on how to set this up.

**Comment by tmds** [comment] 2018-07-12 08:57
From @ManuelAVR in https://github.com/dotnet/corefx/issues/31005#issuecomment-404439094

> We managed with the work arround, we have another proxy server with white lists and this is now working well (without auth).

I'm closing since you were able to resolve the issue.

**Closed by tmds** 2018-07-12 08:57 UTC
