### ISSUE TITLE
Kestrel dotnet 3.1 File Upload Fails for file size above  200KB

### ISSUE THREAD

**Issue by boukisge** [redhat-developer/s2i-dotnetcore#359] opened 2021-04-14 00:39 UTC
We are experiencing an issue with dotnet 3,1 application using kestrel running in openshift 4.4 on-prem. 
File upload via REST API post fails for file size > 200KB . It works for file size under 200kB in the container 

It works fine locally running same code in MS Visual Studio 201

Actual behaviour inside the container: "Read-only file system" exception at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsTContext  for file uploads > 200KB 
file size under 200kb inside the container it works fine

**Comment by tmds** [comment] 2021-04-20 12:45
@boukisge can you share the complete stack trace of the exception?

**Comment by boukisge** [comment] 2021-04-20 16:30
[kestrel issue.docx](https://github.com/redhat-developer/s2i-dotnetcore/files/6345156/kestrel.issue.docx)

**Comment by tmds** [comment] 2021-04-21 13:24
```
System.IO.IOException: Read-only file system
At Interop.ThrowExceptionForIOErrno in /_/src/System.Private.CoreLib/shared/Interop/Unix/Interop.IOErrors.cs:line 24
At Microsoft.Win32.SafeHandles.SafeFileHandle.Open in /_/src/System.Private.CoreLib/shared/Microsoft/Win32/SafeHandles/SafeHandle.Unix.cs: line 39
At System.IO.FileStream.OpenHandle  in /_/src/System.Private.CoreLib/shared/System/IO/FileStream.Unix.cs: line 61
At System.IO.FileStream.ctor  in /_/src/System.Private.CoreLib/shared/System/IO/FileStream.Unix.cs: line 237
At Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.CreateTempFile()
At Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync
At Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAync
At Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync
At Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync
At Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync
At Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync
At Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider
---- End of stack trace from previous location where exception was thrown ----
At Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker
At Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker
At Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow
At Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next
At Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
At Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.
At Microsoft.AspNetCore.Routing.EndpointMiddleware
At Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke
At Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](HttpApplication’1 application)
```

ASP.NET will buffer some files in the file system. For example when using `HttpRequestRewindExtensions.EnableBuffering`. This is also used when uploading files that are higher than a certain size, and is (partly) controllable trough `FormOptions.MemoryBufferThreshold`.

It places files in `Path.GetTempPath()` by default, but the location can be overridden via the `ASPNETCORE_TEMP` envvar.

The exception indicates this location is a read-only filesystem. But maybe it means the location is full.

Can you start a terminal in the container and run `df`, `mount`, and `ls -lah /tmp`?

**Comment by boukisge** [comment] 2021-04-21 14:09
*ls -lsh /tmp*
lrwxrwxrwx 1 root root   pkeypass.pwd
lrwxrwxrwx 1 root root   <pfx file>

*df*
overlay use% 57%
tmp use 1%
/etc/hosts 57%
everything else at 0%

*mount -* anything specific ?

**Comment by tmds** [comment] 2021-04-21 14:22
Are you running these commands in a container that runs the .NET app, and shows the Exception in its logs?

> ls -lsh /tmp*

I'm surprised there are no files from .NET in your `/tmp` folder.

> *mount -* anything specific ?

for mount, we're interested in seeing the flags of `/tmp`.

When I run this in a container on OpenShift, I have 50G free in `/tmp`, and flags show it is mounted `rw`:

```
sh-4.4$ df -h | grep /tmp
/dev/mapper/coreos-luks-root-nocrypt  200G  151G   50G  76% /tmp
sh-4.4$ mount | grep /tmp
/dev/mapper/coreos-luks-root-nocrypt on /tmp type xfs (rw,relatime,seclabel,attr2,inode64,prjquota)
```

Can you write a file in `/tmp` and read it back:
```
sh-4.4$ echo hello >/tmp/test
sh-4.4$ cat /tmp/test
hello
```

**Comment by boukisge** [comment] 2021-04-21 14:28
I get error msg
sh: /tmp/test: Read-only file system

**Comment by boukisge** [comment] 2021-04-21 14:30
fyi - we are using S2I build strategy . Can I edit the assembly script? to
disable read-only option?

**Comment by tmds** [comment] 2021-04-22 12:43
This is not under control of the s2i assemble. The `/tmp` file system gets mounted into the container by the container engine.

You can have a look at the `BuildConfig` and `DeplomentConfig` and see if something might be causing this.

Also check if you can write to `/tmp` in another container (maybe one that doesn't run .NET, or another .NET app). And if that is writable, compare the output of `mount | grep /tmp` between the containers.

Has this app worked previously? Or is this a new app which has not yet worked well on OpenShift?

If that doesn't help you figure out the root cause, please create a support ticket.

**Comment by boukisge** [comment] 2021-04-22 14:08
Thanks, I'll check it out.

**Comment by tmds** [comment] 2021-04-28 12:32
@boukisge I'm going to close this since it is not .NET s2i related and I can't help you further. Have you figured out the root cause?

**Closed** 2021-04-28 12:32 UTC
