### ISSUE TITLE
dotnet restore gives timeout after 100000ms errors when running with low cpu limits

### ISSUE THREAD

**Issue by gest01** [redhat-developer/s2i-dotnetcore#223] opened 2018-09-11 19:29 UTC
The s2i builder image should support all `dotnet restore` options as described here [https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#options](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#options)

I am especially interested in the **--disable-parallel** option, cause we have some issues when restoring packages

kind regards

**Comment by tmds** [comment] 2018-09-11 20:03
> cause we have some issues when restoring packages

Is there an issue for this behavior in dotnet/cli repo?
Maybe the issue is solved in a later version of the sdk? The s2i builder defaults to the lowest sdk for backwards compatibility. To use a later version you can set `DOTNET_SDK_VERSION` to `latest` or a specific version (e.g. `2.1.400`). Alternatively, you can add a `global.json` file to your source repo and set the sdk version there.

We avoid adding open-ended environment variables to the builder because it is hard to ensure they remain backwards compatible.

**Comment by gest01** [comment] 2018-09-12 19:08
> Is there an issue for this behavior in dotnet/cli repo?

Not really..The Problem has something todo with our Enterprise OpenShift Environment and the connection to the internal Nexus Proxy (used for all kinds of package management tool like bower, npm, nuget). 

When i do a dotnet restore using this s2i dotnet builder, we always get an timeout error after 100000ms..This is **not** an error of this S2I Builder, I just want to try the **--disable-parallel** option.

When i do the same with our on-premise TFS environment (connected to the same nexus proxy) **dotnet restore** works as expected

**Comment by tmds** [comment] 2018-09-13 05:05
> No such device or address

@magick93 This is a problem resolving the host name.

> we always get an timeout error after 100000ms

@gest01 have you tried using the 2.1.401 sdk?

**Comment by magick93** [comment] 2018-09-13 05:38
> @magick93 This is a problem resolving the host name.

Thanks @tmds - this makes sense. In the `build.sh` I had to modify line 68 to be 
```
    pushd ${path} &>/dev/null
      docker build -f ${docker_filename} -t ${name} . --add-host nexus.MyCo.global:xx.xx.xx.xx
      check_result_msg $? "Building Docker image ${name} FAILED!"
    popd &>/dev/null
```

But I'm unable to run `s2i build ` with the `--add-host` flag. Do you have any suggestions?

**Comment by tmds** [comment] 2018-09-13 07:34
> But I'm unable to run s2i build with the --add-host flag. Do you have any suggestions?

I don't see an option on s2i to add a host ip either. Maybe your can use the IP address in the DOTNET_RESTORE_SOURCES

**Comment by gest01** [comment] 2018-09-16 19:12
yes, i've already tried using the 2.1.401 sdk..same problem

**Comment by tmds** [comment] 2018-09-17 15:29
There is an issue reported that `dotnet restore` is slow when running on _slow machines_: https://github.com/NuGet/Home/issues/6742.
What kind of limits do you have set for your build pods?
Can you try `--disable-parallel` using a custom assemble script and see how it affects your builds?

**Comment by kareiva** [comment] 2018-09-19 06:07
We are also affected by this, with 50 cpu requests /  200 cpu limits per build pod (from limit ranges).

Adding `--disable-parallel` solves the issue, but there is yet no way to set it through an environment variable (i.e. enforce the default on the openshift cluster level).

**Comment by tmds** [comment] 2018-09-20 12:00
The s2i builder will support controlling this via an envvar: https://github.com/redhat-developer/s2i-dotnetcore/pull/228

**Comment by tmds** [comment] 2018-09-23 12:18
Fixed in https://github.com/redhat-developer/s2i-dotnetcore/pull/228.

**Closed by tmds** 2018-09-23 12:18 UTC

**Comment by madhusudhan-v** [comment] 2019-09-20 06:31
office network is the only issue for me... so use some personal network then it works well

**Comment by tmds** [comment] 2019-09-20 07:08
If you're building ASP.NET Core 2.x webapps, this will help: https://developers.redhat.com/blog/2019/07/10/improving-asp-net-core-build-speed-on-red-hat-openshift/
